version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dataset/ecommerce-session-bigquery.csv:/docker-entrypoint-initdb.d/ecommerce-session-bigquery.csv
    ports:
      - "5432:5432"

volumes:
  db_data: